name: ExplosiveMessenger
version: 0.1
main: com.explosivenetwork.ExplosiveMessenger.Client.ExplosiveMessenger
commands:
   a:
      description: Join a team
      usage: blaa/join <Team> blarUse team r or red to join the red team, use b or blue to join the blue team. Use join o or obs to join the observers.
      permission: join
      permission-message: You don't have permissions to do that
   br:
      description: Join a team
      usage: blaa/join <Team> blarUse team r or red to join the red team, use b or blue to join the blue team. Use join o or obs to join the observers.
      permission: join
      permission-message: You don't have permissions to do that
   applyv:
      description: Join a team
      usage: blaa/join <Team> blarUse team r or red to join the red team, use b or blue to join the blue team. Use join o or obs to join the observers.
      permission: join
      permission-message: You don't have permissions to do tha